name: CustomRecipe
version: '${project.version}'
main: com.senko.customrecipe.CustomRecipe
api-version: 1.18
authors: [ senko ]
description: 自定义物品合成
depend: [CustomEventPlugin]
commands:
  villager:
    description: 生成一只特殊的村民