senko:
  list:           #list
    - 1
    - 2
    - abc
  map:            #MapList
    - {name: senko, count: 1, speed: 3.3f}
    - {name: senko2, count: 2, speed: 2.2f}
  age: 11         #11
  disabled: false #false