name: CustomEventPlugin
version: '${project.version}'
main: com.senko.customeventplugin.CustomEventPlugin
api-version: 1.18
authors: [ senko ]
description: 自定义事件
commands:
  godbow:
    usage: /godbow
    description: 给自己发一把类似于Hypixel的Modular Bow
    permission: senko.godbow